### ISSUE TITLE
git clone --recursive

### ISSUE THREAD

**Issue by keevee09** [allthemusicllc/atm-cli#10] opened 2020-02-15 03:24 UTC
The installation instructions need to include `--recurisive` in the git clone line.

`git clone --recursive https://github.com/allthemusicllc/atm-cli.git`

Thank you for your efforts to prevent copyright madness!

**Comment by allthemusicllc** [comment] 2020-02-16 18:32
Duplicate of #9

**Closed** 2020-02-16 18:35 UTC
